#!/bin/bash

my_laptop_external_monitor=$(xrandr --query | grep 'eDP')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rotate normal --output eDP --off &&
    xrandr --output HDMI-A-0 --set underscan on --set "underscan vborder" 40 --set "underscan hborder" 72
fi
