#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## BSPWM config file for Archcraft

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#5294E2'
BSPWM_NBC='#1E2128'
BSPWM_ABC='#C778DD'
BSPWM_PFC='#98C379'

## Bspwm appearance
BSPWM_BORDER='2'
BSPWM_GAP='10'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manager Workspaces
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6' '7' '8'
		bspc monitor ${monitor} -n "$name" -d '一' '二' '三' '四' '五' '六' '七' '八'
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces
#bspc monitor eDP -d 一 二 三 四 五 
#bspc monitor HDMI-A-0 -d 九 十

## Apply bspwm configurations
bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config top_padding 38

bspc config focused_border_color \#6398C6
bspc config normal_border_color \#040421
bspc config active_border_color \#040421
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*


## Always Floating Apps
bspc rule -a kitty:Float state=floating follow=on focus=on center=true rectangle=900x600+0+0
bspc rule -a discord state=floating follow=on focus=on center=true rectangle=1000x700+0+0
bspc rule -a TelegramDesktop state=floating follow=on focus=on center=true rectangle=1000x700+0+0
bspc rule -a Nitrogen state=floating follow=on focus=on center=true rectangle=900x600+0+0
bspc rule -a Viewnior state=floating follow=on focus=on center=true
bspc rule -a feh state=floating follow=on focus=on
bspc rule -a Nm-connection-editor state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Yad state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Lxappearance state=floating desktop=^5 center=true rectangle=800x500+0+0
bspc rule -a Blueman-manager state=floating center=true rectangle=800x500+0+0
bspc rule -a Pavucontrol state=floating center=true rectangle=800x500+0+0

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
nitrogen --restore &

# Start bspwm scripts
bspbar
bspcomp
bspdunst
bspfloat &

